const path = require("path");
require("dotenv").config({ path: path.resolve(__dirname, "../.env") });
const mongoose = require("mongoose");
const connectDB = require("../config/db");
const Product = require("../models/Product");

const products = [
    // ── Soft Drinks ──
    {
        name: "Coca-Cola Classic",
        price: 40,
        originalPrice: 50,
        category: "Soft Drinks",
        image: "https://images.unsplash.com/photo-1627338348208-dc098cbfca36?w=400&q=80",
        description: "The world's favorite cola, refreshing and crisp.",
        stock: 100,
        unit: "750ml",
        brand: "Coca-Cola",
        rating: 4.8,
        reviewCount: 1250,
        isFeatured: true,
    },
    {
        name: "Pepsi Cola",
        price: 40,
        originalPrice: 50,
        category: "Soft Drinks",
        image: "https://images.unsplash.com/photo-1734605641773-f2755bf7432d?w=400&q=80",
        description: "Bold, refreshing cola with a modern twist.",
        stock: 85,
        unit: "750ml",
        brand: "Pepsi",
        rating: 4.7,
        reviewCount: 980,
        isFeatured: false,
    },
    {
        name: "Sprite Lemon Lime",
        price: 38,
        originalPrice: 45,
        category: "Soft Drinks",
        // Replaced Dove cream with actual Lemon/Lime drink
        image: "https://plus.unsplash.com/premium_photo-1681236320994-3395e842ed81?w=400&q=80",
        description: "Crisp, clean lemon-lime taste with no caffeine.",
        stock: 70,
        unit: "750ml",
        brand: "Sprite",
        rating: 4.6,
        reviewCount: 870,
        isFeatured: false,
    },
    {
        name: "Mountain Dew",
        price: 40,
        originalPrice: 48,
        category: "Soft Drinks",
        image: "https://images.unsplash.com/photo-1687850020044-2a6adede49cd?w=400&q=80",
        description: "Exhilarating citrus rush with bold flavor.",
        stock: 60,
        unit: "750ml",
        brand: "Pepsi",
        rating: 4.5,
        reviewCount: 760,
        isFeatured: false,
    },
    {
        name: "Thums Up",
        price: 38,
        originalPrice: 45,
        category: "Soft Drinks",
        image: "https://images.unsplash.com/photo-1617981292120-3c56b766e2a7?w=400&q=80",
        description: "India's own strong cola with a bold taste.",
        stock: 90,
        unit: "750ml",
        brand: "Coca-Cola",
        rating: 4.7,
        reviewCount: 1100,
        isFeatured: false,
    },
    {
        name: "Limca Lemon",
        price: 35,
        originalPrice: 42,
        category: "Soft Drinks",
        image: "https://images.unsplash.com/photo-1617981291730-b989878620b8?w=400&q=80",
        description: "Lemony fresh fizz you can feel.",
        stock: 55,
        unit: "750ml",
        brand: "Coca-Cola",
        rating: 4.4,
        reviewCount: 620,
        isFeatured: false,
    },
    {
        name: "Fanta Orange",
        price: 38,
        originalPrice: 45,
        category: "Soft Drinks",
        image: "https://plus.unsplash.com/premium_photo-1678148681597-d519e9a1f0ba?w=400&q=80",
        description: "Bubbling orange goodness in every sip.",
        stock: 65,
        unit: "750ml",
        brand: "Coca-Cola",
        rating: 4.5,
        reviewCount: 710,
        isFeatured: false,
    },
    {
        name: "7UP Refresher",
        price: 35,
        originalPrice: 42,
        category: "Soft Drinks",
        image: "https://images.unsplash.com/photo-1651806356904-7dfe545d7858?w=400&q=80",
        description: "Light, lemon refreshment without the caffeine.",
        stock: 50,
        unit: "750ml",
        brand: "PepsiCo",
        rating: 4.4,
        reviewCount: 580,
        isFeatured: false,
    },

    // ── Energy Drinks ──
    {
        name: "Red Bull Original",
        price: 125,
        originalPrice: 150,
        category: "Energy Drinks",
        image: "https://images.unsplash.com/photo-1603833787096-4ab5f6706814?w=400&q=80",
        description: "Gives you wings! The world's #1 energy drink.",
        stock: 45,
        unit: "250ml",
        brand: "Red Bull",
        rating: 4.8,
        reviewCount: 2100,
        isFeatured: true,
    },
    {
        name: "Red Bull Sugar Free",
        price: 125,
        originalPrice: 150,
        category: "Energy Drinks",
        image: "https://images.unsplash.com/photo-1643373976548-b6e76c05ef44?w=400&q=80",
        description: "All the energy, no sugar. Zero compromise.",
        stock: 40,
        unit: "250ml",
        brand: "Red Bull",
        rating: 4.7,
        reviewCount: 1450,
        isFeatured: false,
    },
    {
        name: "Monster Energy Original",
        price: 110,
        originalPrice: 130,
        category: "Energy Drinks",
        image: "https://plus.unsplash.com/premium_photo-1664305046686-8fb0b095617e?w=400&q=80",
        description: "Unleash the beast! Packed with energy blend.",
        stock: 38,
        unit: "500ml",
        brand: "Monster",
        rating: 4.6,
        reviewCount: 1800,
        isFeatured: false,
    },
    {
        name: "Sting Energy Drink",
        price: 45,
        originalPrice: 55,
        category: "Energy Drinks",
        image: "https://images.unsplash.com/photo-1501474587451-40f1e29a4223?w=400&q=80",
        description: "Powerful energy fusion with vitamin B.",
        stock: 80,
        unit: "250ml",
        brand: "PepsiCo",
        rating: 4.3,
        reviewCount: 920,
        isFeatured: false,
    },
    {
        name: "Hell Energy Drink",
        price: 99,
        originalPrice: 120,
        category: "Energy Drinks",
        image: "https://images.unsplash.com/photo-1566846128021-b940b0eec910?w=400&q=80",
        description: "Hell yeah! Extreme energy for extreme moments.",
        stock: 30,
        unit: "250ml",
        brand: "Hell",
        rating: 4.2,
        reviewCount: 450,
        isFeatured: false,
    },

    // ── Juices ──
    {
        name: "Tropicana Orange",
        price: 55,
        originalPrice: 65,
        category: "Juices",
        image: "https://images.unsplash.com/photo-1622597467821-df79dcb4f94d?w=400&q=80",
        description: "100% pure squeezed orange juice, no pulp.",
        stock: 75,
        unit: "1L",
        brand: "Tropicana",
        rating: 4.7,
        reviewCount: 1350,
        isFeatured: true,
    },
    {
        name: "Real Mixed Fruit Juice",
        price: 48,
        originalPrice: 58,
        category: "Juices",
        image: "https://plus.unsplash.com/premium_photo-1675667756988-e73d68e5abf1?w=400&q=80",
        description: "Blend of tropical fruits in every pack.",
        stock: 65,
        unit: "1L",
        brand: "Real",
        rating: 4.5,
        reviewCount: 980,
        isFeatured: false,
    },
    {
        name: "Minute Maid Pulpy Orange",
        price: 50,
        originalPrice: 60,
        category: "Juices",
        image: "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=400&q=80",
        description: "With real orange pulp for extra freshness.",
        stock: 70,
        unit: "1L",
        brand: "Minute Maid",
        rating: 4.6,
        reviewCount: 1100,
        isFeatured: false,
    },
    {
        name: "Frooti Mango",
        price: 20,
        originalPrice: 25,
        category: "Juices",
        image: "https://images.unsplash.com/photo-1614707585284-9cb9fc018387?w=400&q=80",
        description: "India's favorite mango drink, fresh ho jao!",
        stock: 120,
        unit: "200ml",
        brand: "Parle Agro",
        rating: 4.6,
        reviewCount: 2200,
        isFeatured: true,
    },
    {
        name: "Appy Fizz Sparkling",
        price: 30,
        originalPrice: 38,
        category: "Juices",
        image: "https://images.unsplash.com/photo-1546173159-315724a31696?w=400&q=80",
        description: "Sparkling apple drink with a fizzy twist.",
        stock: 85,
        unit: "300ml",
        brand: "Parle Agro",
        rating: 4.4,
        reviewCount: 780,
        isFeatured: false,
    },
    {
        name: "Paper Boat Aamras",
        price: 35,
        originalPrice: 42,
        category: "Juices",
        image: "https://plus.unsplash.com/premium_photo-1667543228378-ec4478ab2845?w=400&q=80",
        description: "Authentic mango pulp drink, like grandma made.",
        stock: 60,
        unit: "200ml",
        brand: "Paper Boat",
        rating: 4.7,
        reviewCount: 1450,
        isFeatured: false,
    },
    {
        name: "Paper Boat Jamun Kala Khatta",
        price: 35,
        originalPrice: 42,
        category: "Juices",
        image: "https://images.unsplash.com/photo-1619241638225-14d56e47ae64?w=400&q=80",
        description: "The tangy jamun drink that takes you back home.",
        stock: 45,
        unit: "200ml",
        brand: "Paper Boat",
        rating: 4.5,
        reviewCount: 870,
        isFeatured: false,
    },
    {
        name: "Real Cranberry Juice",
        price: 85,
        originalPrice: 100,
        category: "Juices",
        image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&q=80",
        description: "Tart and tangy cranberry goodness.",
        stock: 35,
        unit: "1L",
        brand: "Real",
        rating: 4.4,
        reviewCount: 520,
        isFeatured: false,
    },

    // ── Water ──
    {
        name: "Bisleri Mineral Water",
        price: 20,
        originalPrice: 25,
        category: "Water",
        image: "https://images.unsplash.com/photo-1554171595-4547fca1d379?w=400&q=80",
        description: "Pure and safe drinking water, always trustworthy.",
        stock: 200,
        unit: "1L",
        brand: "Bisleri",
        rating: 4.5,
        reviewCount: 3200,
        isFeatured: false,
    },
    {
        name: "Evian Natural Spring Water",
        price: 120,
        originalPrice: 140,
        category: "Water",
        image: "https://plus.unsplash.com/premium_photo-1678837556047-3ade94f1ecc5?w=400&q=80",
        description: "Premium alpine spring water from the French Alps.",
        stock: 50,
        unit: "750ml",
        brand: "Evian",
        rating: 4.7,
        reviewCount: 890,
        isFeatured: false,
    },
    {
        name: "Kinley Drinking Water",
        price: 15,
        originalPrice: 20,
        category: "Water",
        image: "https://images.unsplash.com/photo-1560847468-5eef330f455a?w=400&q=80",
        description: "Safe, clean drinking water for everyday use.",
        stock: 180,
        unit: "1L",
        brand: "Coca-Cola",
        rating: 4.3,
        reviewCount: 1560,
        isFeatured: false,
    },
    {
        name: "Qua Sparkling Water",
        price: 60,
        originalPrice: 75,
        category: "Water",
        image: "https://images.unsplash.com/photo-1523362628745-0c100150b504?w=400&q=80",
        description: "Crisp sparkling natural water with fine bubbles.",
        stock: 40,
        unit: "500ml",
        brand: "Coca-Cola",
        rating: 4.4,
        reviewCount: 320,
        isFeatured: false,
    },

    // ── Tea & Coffee ──
    {
        name: "Nestea Iced Lemon Tea",
        price: 30,
        originalPrice: 38,
        category: "Tea & Coffee",
        image: "https://images.unsplash.com/photo-1631155989916-4aabcabcce8d?w=400&q=80",
        description: "Refreshing iced tea with real lemon flavor.",
        stock: 70,
        unit: "300ml",
        brand: "Nestlé",
        rating: 4.4,
        reviewCount: 760,
        isFeatured: false,
    },
    {
        name: "Starbucks Cold Brew Coffee",
        price: 180,
        originalPrice: 210,
        category: "Tea & Coffee",
        image: "https://plus.unsplash.com/premium_photo-1683133572097-c005bddbcbf5?w=400&q=80",
        description: "Smooth and bold cold brew, ready to sip.",
        stock: 25,
        unit: "250ml",
        brand: "Starbucks",
        rating: 4.8,
        reviewCount: 1850,
        isFeatured: false,
    },
    {
        name: "Chaayos Masala Chai",
        price: 55,
        originalPrice: 65,
        category: "Tea & Coffee",
        image: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=400&q=80",
        description: "Packed with real Indian spices & Assam tea.",
        stock: 40,
        unit: "200ml",
        brand: "Chaayos",
        rating: 4.6,
        reviewCount: 620,
        isFeatured: false,
    },
    {
        name: "Nescafé Mochaccino RTD",
        price: 75,
        originalPrice: 90,
        category: "Tea & Coffee",
        image: "https://images.unsplash.com/photo-1642867705856-2a0ecde1399b?w=400&q=80",
        description: "Creamy mocha flavored ready-to-drink coffee.",
        stock: 35,
        unit: "180ml",
        brand: "Nestlé",
        rating: 4.5,
        reviewCount: 530,
        isFeatured: false,
    },
    {
        name: "TE-A-ME Green Tea",
        price: 45,
        originalPrice: 55,
        category: "Tea & Coffee",
        image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&q=80",
        description: "Organic green tea, light and antioxidant-rich.",
        stock: 55,
        unit: "300ml",
        brand: "TE-A-ME",
        rating: 4.3,
        reviewCount: 380,
        isFeatured: false,
    },

    // ── Dairy Drinks ──
    {
        name: "Amul Kool Milk",
        price: 25,
        originalPrice: 30,
        category: "Dairy Drinks",
        image: "https://images.unsplash.com/photo-1761064490619-0aea9d301d6e?w=400&q=80",
        description: "Chilled flavored milk, wholesome and delicious.",
        stock: 90,
        unit: "200ml",
        brand: "Amul",
        rating: 4.5,
        reviewCount: 1450,
        isFeatured: false,
    },
    {
        name: "Amul Kool Chocolate Milk",
        price: 28,
        originalPrice: 35,
        category: "Dairy Drinks",
        image: "https://plus.unsplash.com/premium_photo-1694481099872-29a6ece2672c?w=400&q=80",
        description: "Rich chocolate-flavored chilled milk.",
        stock: 80,
        unit: "200ml",
        brand: "Amul",
        rating: 4.6,
        reviewCount: 1680,
        isFeatured: false,
    },
    {
        name: "Lassi by Epigamia",
        price: 75,
        originalPrice: 90,
        category: "Dairy Drinks",
        // Replaced broken placeholder
        image: "https://images.unsplash.com/photo-1610219171293-e9809faf73bd?w=400&q=80",
        description: "Artisanal mango lassi made with real yogurt.",
        stock: 30,
        unit: "180ml",
        brand: "Epigamia",
        rating: 4.7,
        reviewCount: 720,
        isFeatured: false,
    },
    {
        name: "Mother Dairy Chaas",
        price: 20,
        originalPrice: 25,
        category: "Dairy Drinks",
        // Replaced broken placeholder
        image: "https://images.unsplash.com/photo-1720355340824-cd9f183ab0e3?w=400&q=80",
        description: "Traditional spiced buttermilk, light and refreshing.",
        stock: 60,
        unit: "200ml",
        brand: "Mother Dairy",
        rating: 4.4,
        reviewCount: 890,
        isFeatured: false,
    },

    // ── Sports Drinks ──
    {
        name: "Gatorade Lemon Charge",
        price: 85,
        originalPrice: 100,
        category: "Sports Drinks",
        image: "https://images.unsplash.com/photo-1580955027067-8ef70ef0c1cf?w=400&q=80",
        description: "Replenish electrolytes and fuel your performance.",
        stock: 55,
        unit: "500ml",
        brand: "Gatorade",
        rating: 4.6,
        reviewCount: 1150,
        isFeatured: false,
    },
    {
        name: "Gatorade Orange Rush",
        price: 85,
        originalPrice: 100,
        category: "Sports Drinks",
        image: "https://plus.unsplash.com/premium_photo-1661962299761-33b8af92c995?w=400&q=80",
        description: "Orange flavor electrolyte drink for athletes.",
        stock: 45,
        unit: "500ml",
        brand: "Gatorade",
        rating: 4.5,
        reviewCount: 870,
        isFeatured: false,
    },
    {
        name: "ORS Apple Flavor",
        price: 35,
        originalPrice: 42,
        category: "Sports Drinks",
        // Replaced samosa image with Apple juice
        image: "https://images.unsplash.com/photo-1506353219544-65860ffc5f41?w=400&q=80",
        description: "Oral rehydration electrolytes in apple flavor.",
        stock: 70,
        unit: "200ml",
        brand: "Enerzal",
        rating: 4.2,
        reviewCount: 460,
        isFeatured: false,
    },
    {
        name: "Powerade Mountain Berry",
        price: 90,
        originalPrice: 110,
        category: "Sports Drinks",
        // Replaced broken image with blue sports drink
        image: "https://images.unsplash.com/photo-1516116189403-10c54c714a28?w=400&q=80",
        description: "ION4® electrolyte system for superior hydration.",
        stock: 40,
        unit: "500ml",
        brand: "Coca-Cola",
        rating: 4.3,
        reviewCount: 380,
        isFeatured: false,
    },

    // ── Mocktails ──
    {
        name: "Svami Watermelon Mojito",
        price: 95,
        originalPrice: 115,
        category: "Mocktails",
        image: "https://images.unsplash.com/photo-1570598912132-0ba1dc952b7d?w=400&q=80",
        description: "Premium watermelon and mint mocktail, alcohol-free.",
        stock: 30,
        unit: "250ml",
        brand: "Svami",
        rating: 4.7,
        reviewCount: 520,
        isFeatured: false,
    },
    {
        name: "Raw Pressery Ginger Limeade",
        price: 80,
        originalPrice: 95,
        category: "Mocktails",
        image: "https://plus.unsplash.com/premium_photo-1670333183316-ab697ddd9b13?w=400&q=80",
        description: "Zesty ginger and lime cold-pressed mocktail.",
        stock: 25,
        unit: "250ml",
        brand: "Raw Pressery",
        rating: 4.5,
        reviewCount: 340,
        isFeatured: false,
    },
    {
        name: "Soda Factory Blue Lagoon",
        price: 70,
        originalPrice: 85,
        category: "Mocktails",
        image: "https://images.unsplash.com/photo-1592858167090-2473780d894d?w=400&q=80",
        description: "Blue curacao-inspired tropical non-alcoholic drink.",
        stock: 35,
        unit: "300ml",
        brand: "Soda Factory",
        rating: 4.4,
        reviewCount: 280,
        isFeatured: false,
    },
    {
        name: "B-Fizz Apple Cocktail",
        price: 35,
        originalPrice: 42,
        category: "Mocktails",
        image: "https://images.unsplash.com/photo-1587223962930-cb7f31384c19?w=400&q=80",
        description: "Sparkling apple mocktail, the party in a can.",
        stock: 60,
        unit: "300ml",
        brand: "Parle Agro",
        rating: 4.4,
        reviewCount: 650,
        isFeatured: false,
    },
    {
        name: "Coco Pina Colada Mocktail",
        price: 90,
        originalPrice: 110,
        category: "Mocktails",
        image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=400&q=80",
        description: "Pineapple & coconut bliss, no alcohol needed.",
        stock: 20,
        unit: "250ml",
        brand: "Coco Co.",
        rating: 4.6,
        reviewCount: 310,
        isFeatured: false,
    },
    {
        name: "Virgin Sangria Punch",
        price: 85,
        originalPrice: 100,
        category: "Mocktails",
        image: "https://plus.unsplash.com/premium_photo-1671647122910-3fa8ab4990cb?w=400&q=80",
        description: "Spanish-inspired fruity punch without the wine.",
        stock: 28,
        unit: "300ml",
        brand: "Soda Factory",
        rating: 4.5,
        reviewCount: 270,
        isFeatured: false,
    },
];

const seedDB = async () => {
    try {
        await connectDB();
        console.log("🗑  Clearing existing products...");
        await Product.deleteMany({});
        console.log("🌱 Seeding products...");
        const created = await Product.insertMany(products);
        console.log(`✅ ${created.length} products seeded successfully!`);
        process.exit(0);
    } catch (error) {
        console.error("❌ Seed error:", error.message);
        process.exit(1);
    }
};

seedDB();
